---
title: "Oh, you found my secret GitHub page, congratulations!"
output:
  html_document:
    self_contained: true
    includes:
      in_header: "favicon.html"
  github_document:
    df_print: default
knit: (function(input, encoding) { rmarkdown::render(input, encoding = encoding, output_format = "html_document", output_file = "index.html"); rmarkdown::render(input, encoding = encoding, output_format = "github_document", output_file = "README.md"); "README.md" })
---

However, you might have more luck looking at my official website: [https://remi-theriault.com/](https://remi-theriault.com/)

Also, kudos! As a bonus, you get to see the exclusive list of all my packages:

### CRAN Packages

```{r cran_pkgs, echo=FALSE, message=FALSE, warning=FALSE}
source("helpers.R")

author <- "Rémi Thériault"
cran_pkgs <- c("rempsyc", "lavaanExtra")
cran_data <- fetch_cran_data(author, pkgs = cran_pkgs)

make_dt_with_hex(cran_data)
```

### easystats Packages

```{r easystats_pkgs, echo=FALSE, message=FALSE}
easystats_pkgs <- c("performance", "effectsize", 
                    "correlation", "see", "modelbased", "easystats", "report")
easystats_data <- fetch_cran_data(author, pkgs = easystats_pkgs)

make_dt_with_hex(easystats_data)
```

### Packages on R-Universe Only

```{r runiverse_data, echo=FALSE, message=FALSE}
runiverse_data_rempsyc <- fetch_runiverse_data(
  author = "rempsyc",
  pkgs_exclude = c(
    cran_pkgs,
    "pubmedDashboard",
    "waffle",
    "ggflags"
  )
)

runiverse_data_centerconflictcooperation <- fetch_runiverse_data(
  author = "centerconflictcooperation"
)

runiverse_data <- bind_rows(
  runiverse_data_rempsyc,
  runiverse_data_centerconflictcooperation)

make_dt_with_hex(runiverse_data)
```

### Other Contributions

```{r cont_pkgs, echo=FALSE, message=FALSE}
cont_pkgs <- c("insight", "datawizard", "flextable")
cont_data <- fetch_cran_data(author, pkgs = cont_pkgs)

make_dt_with_hex(cont_data)
```
